import type { Metadata } from "next";
import { Inter, Kdam_Thmor_Pro } from "next/font/google";
import "./globals.css";
// import Footer from "@/feature/layout/Footer";
// import { ThemeProvider } from "@/theme/ThemeProvider";
// import Header from "@/feature/layout/Header";
import { getAuthSession } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { ThemeProvider } from "@/theme/theme-provider";
import clsx from "clsx";
import NoConect from "@/components/NoConect";
import Link from "next/link";
import {
  AlertCircle,
  LucidePiggyBank,
  PiggyBank,
  SettingsIcon,
} from "lucide-react";
import { ModeToggle } from "@/components/ModeToggle";
import Montant from "@/components/portefeuille/Montant";
import { DrawerDialogDemo } from "@/components/portefeuille/formulaire";
import { BreadcrumbWithCustomSeparator } from "@/components/Breadcrumbs";

// import NoUser from "@/components/NoUser";

const inter = Inter({ subsets: ["latin"] });
const kdam_Thmor_Pro = Kdam_Thmor_Pro({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuthSession();
  return (
    <html lang="en" className={clsx(kdam_Thmor_Pro.className, "h-full")}>
      <body>
        <div className="flex flex-col h-full" style={{ height: "100vh" }}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex-1 max-w-lg m-auto w-full bg-blue-400 dark:bg-blue-900">
              {session ? (
                <>
                  <div className="flex items-center justify-between p-3">
                    <Link href="/settings">
                      <SettingsIcon />
                    </Link>
                    <ModeToggle />
                  </div>
                  <div className="flex flex-col items-center sticky top-0 ">
                    <div className="w-full  text-center text-5xl flex items-end justify-center py-8  bg-blue-400 dark:bg-blue-900 ">
                      <Montant />
                    </div>
                    <div className="w-full flex justify-around px-10 sm:px-20  py-5  bg-white dark:bg-black rounded-se-3xl rounded-ss-3xl ">
                      <DrawerDialogDemo />
                      <Link
                        href="/groupe"
                        className="flex flex-col items-center gap-2 text-sm"
                      >
                        <div className="dark:bg-blue-900 bg-blue-400  p-4 rounded-full  ">
                          <PiggyBank size="30" />
                        </div>
                        Les Groupes
                      </Link>
                      <Link
                        href="/"
                        className="flex flex-col items-center gap-2 text-sm"
                      >
                        <div className="dark:bg-blue-900 bg-blue-400 p-4 rounded-full  ">
                          <AlertCircle size="30" />
                        </div>
                        Indisponible
                      </Link>
                    </div>
                    <BreadcrumbWithCustomSeparator />
                  </div>
                  {children}
                </>
              ) : (
                <NoConect />
              )}
            </div>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
